version: 2

models:
  - name: stg_carmen_sightings
    description: "Staging view, combines all sources into one common dictionary"

    columns:
      - name: date_witness
        description: "{{ doc('date_witness') }}"

      - name: date_agent
        description: "{{ doc('date_agent') }}"

      - name: witness
        descrition: "Name of witness sighting the perpetrator"

      - name: agent
        description: "Name of field agent filing the report"

      - name: latitude
        description: "{{ doc('latitude') }}"

      - name: longitude
        description: "{{ doc('longitude') }}"

      - name: city
        description: "{{ doc('city') }}"

      - name: country
        description: "{{ doc('country') }}"

      - name: city_agent
        description: "{{ doc('city_agent') }}"

      - name: has_weapon
        description: "{{ doc('has_weapon') }}"

      - name: has_hat
        description: "{{ doc('has_hat') }}"

      - name: has_jacket
        description: "{{ doc('has_jacket') }}"

      - name: behavior
        description: "{{ doc('behavior') }}"

      - name: agency_region
        description: "{{ doc('agency_region') }}"
